### ISSUE TITLE
Cannot install on local Ubuntu 16.04

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/pepyatka-ansible#48]
Hi,
I have difficulty installing freefeed-ansible on my local  Ubuntu 16.04 64bit machine. 

> vagrant --version:  1.8.1

VAGRANTFILE:

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.ssh.forward_agent = true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/site.yml"
    ansible.sudo = true
    ansible.groups = {
      "pepyatka" => ["default"],
      "nginx" => ["default"],
      "redis" => ["default"]
    }
    ansible.extra_vars = {
      pepyatka_hostname: "localhost:8080",
      pepyatka_server_repo: "https://github.com/FreeFeed/freefeed-ansible.git",
      pepyatka_server_branch: "development",
      pepyatka_html_repo: "https://github.com/FreeFeed/freefeed-react-client.git",
      pepyatka_html_branch: "development"
    }
    ansible.raw_arguments = ENV['ANSIBLE_ARGS']
  end
end
```

dev:
```
[target]
localhost

[redis:children]
target

[postgres:children]
target

[pepyatka:children]
target

[pepyatka-frontend:children]
target

```
When I try to run vagrant:

```
me@pc:~/pepyatka-ansible$ ansible-playbook -i local playbooks/site.yml --connection=local
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 41, in <module>
    from ansible.utils.unicode import to_unicode
ImportError: cannot import name to_unicode
```

Really appreciate your help to fix this.

**Comment by indeyets** [comment]
@k0fi thanks for the report.

our current official configuration is:

* Debian Jessie
* Python 2.7.9
* Ansible 2.1.2

Both Ubuntu and Vagrant were not tested in quite awhile.

Still, it is possible that you would be able to move much further by aligning Ansible version.

**Comment by k0fi** [comment]
Alright, I'll test on Debian Jessie. Can you please confirm that my config files are correct?

**Comment by indeyets** [comment]
@id can you take a look here, please?

**Comment by k0fi** [comment]
Well I've install ansible `2.5.1` but still get the same error:

```
me@pc:~/freefeed-ansible$ ansible-playbook -i local playbooks/site.yml --connection=local
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 41, in <module>
    from ansible.utils.unicode import to_unicode
ImportError: cannot import name to_unicode
```

**Comment by id** [comment]
@k0fi are you trying this on Debian jessie server directly?
Could you tell how exactly did you install ansible there?

**Comment by k0fi** [comment]
No I tried it on Ubuntu 16.04. Then given up and install FF directly. 
The current docs is really lacking for someone who already does not know these crapware containers.

**Comment by silpol** [comment]
Python 2 is obsolete
Ubuntu 16.04 is EOL
time to WONTFIX/CLOSE this bug
